[capture]
target = "camera"

[communicate]
enable = true

[video]
path = ""

[image]
path = ""

[camera]
id = 1
exposure_time = 9940.0 # 100FPS
# exposure_time = 20000.0 # calibration

gain = 16.0
white_balance_red = 1.6
white_balance_blue = 1.7
calibration_file = "./result.xml"

[model]
bin_file = "/home/rm/models/model-opt-int8.bin"
xml_file = "/home/rm/models/model-opt-int8.xml"

[ekf]
q = [0.1, 100.0, 0.1, 100.0, 0.1, 100.0]
r = [1.0, 1.0, 300.0]

[serial]
port = "/dev/ttyUSB0"
baud_rate = 115200

[vofa]
enable = true
ip = "192.168.137.1"
port = 1347

[debug]
enable_window = false