[capture]
target = "camera"

[communicate]
enable = true

[video]
path = "/home/rm/dataset/Video/哨兵移动.mp4"

[image]
path = ""

[camera]
manufacturer = "dahua"
# 传统视觉
exposure_time = 4000.0
gain = 1.0 # 大恒16.0，大华1.6
# 神经网络
# exposure_time = 9940.0 # 100FPS
# gain = 1.60 # 大恒16.0，大华1.6
# 标定
# exposure_time = 20000.0 
# gain = 3.2

white_balance_red = 1.6
white_balance_blue = 1.7
calibration_file = "./result.xml"

[model]
path = "/home/rm/2022-REDO/asset/fc.onnx"

[kalman_filter]
q = [0.01, 1000.0, 0.01, 1000.0, 0.01, 1000.0]
r = [500.0, 500.0, 500.0]

[serial]
enable = false
port = "/dev/ttyUSB0"
baud_rate = 115200

[vofa]
enable = true
ip = "192.168.137.1" # nuc 共享网络
# ip = "192.168.236.1" # vmware 虚拟机
port = 1347

[debug]
enable_window = true